# Generated by Django 5.2.6 on 2025-10-01 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Введите дату оплаты', verbose_name='Дата оплаты')),
                ('amount', models.PositiveIntegerField(help_text='Введите сумму оплаты', verbose_name='Сумма оплаты')),
                ('type', models.CharField(choices=[('cash', 'Наличные'), ('transaction', 'Перевод')], max_length=12)),
                ('course', models.ForeignKey(help_text='Укажите курс', on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(help_text='Укажите оплаченный урок', on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Укажите плательщика', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
