# Generated by Django 5.2.6 on 2025-11-04 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
        ('users', '0004_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, help_text='Введите дату оплаты', null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Укажите оплаченный урок', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transaction', 'Перевод')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Укажите плательщика', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Плательщик'),
        ),
    ]
