# Generated by Django 5.2.6 on 2025-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_course_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.TextField(blank=True, help_text='Укажите ссылку на оплату', max_length=800, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
