# Generated by Django 5.2.6 on 2025-09-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=100, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью курса', null=True, upload_to='materials/courses_preview/', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Введите описание курса', null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название урока', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью урока', null=True, upload_to='materials/lessons_preview/', verbose_name='Превью')),
                ('video_link', models.URLField(blank=True, help_text='Введите ссылку на видео урока', null=True, verbose_name='Ссылка на видео урока')),
                ('course', models.ForeignKey(blank=True, help_text='Введите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
