# Generated by Django 5.2.6 on 2025-11-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID продукта в Stripe', max_length=255, null=True, verbose_name='Stripe Product ID'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID продукта в Stripe', max_length=255, null=True, verbose_name='Stripe Product ID'),
        ),
    ]
